###
GET http://localhost:4040/odata/v4/review
Authorization: Basic alice:
### T1
GET http://localhost:4040/odata/v4/review/getBookshopServiceManager()
Authorization: Basic alice:
###
GET http://localhost:4040/odata/v4/review/getServiceBindingForTenantId(tenantId='t1')
Authorization: Basic alice:
###
GET http://localhost:4040/odata/v4/review/Reviews
Authorization: Basic alice:
###
POST http://localhost:4040/odata/v4/review/Reviews
Authorization: Basic alice:
Content-Type: application/json

{
  "subject": "1",
  "rating": 3,
  "title": "Average",
  "text": "OK but could be better"
}

### T2
GET http://localhost:4040/odata/v4/review/Reviews
Authorization: Basic erin:
###
# @name getBooks
GET http://localhost:4040/odata/v4/review/Books
Authorization: Basic alice:
###
@bookId={{getBooks.response.body.$.value[0].ID}}
###
PATCH http://localhost:4040/odata/v4/review/Books({{bookId}})
Authorization: Basic alice:
Content-Type: application/json

{
  "stock": 500
}
