# Sidecar
#@port=4005
# Main Service
@port=4040
###
POST http://localhost:{{port}}/-/cds/deployment/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Basic alice:

{ 
  "tenant": "t1"
}
###
POST http://localhost:{{port}}/-/cds/deployment/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Basic erin:

{ 
  "tenant": "t2"
}
